from backend.database import Base
from sqlalchemy import Column, Integer, String, CheckConstraint, event, DDL, text


class User(Base):
    __tablename__ = "users"

    # Fixed 8-digit code stored in DB, e.g. "00000001", "00000002", ...
    # Generated by a Postgres sequence + LPAD.
    user_code = Column(
        String(8),
        primary_key=True,
        nullable=False,
        unique=True,
        server_default=text("lpad(nextval('user_code_seq')::text, 8, '0')")
    )

    first_name = Column(String(50), nullable=False)
    last_name = Column(String(50), nullable=False)
    email = Column(String(255), nullable=False, unique=True, index=True)
    password_hash = Column(String(255), nullable=False)
    mobile_number = Column(String(20), nullable=True)

    # Store as VARCHAR; you can enforce allowed values with CHECK if you want
    user_role = Column(String(20), nullable=False, server_default="SME")

    __table_args__ = (
        CheckConstraint("char_length(user_code) = 8", name="chk_user_code_len"),
        CheckConstraint("user_role IN ('SME','STAFF')", name="chk_user_role_valid"),
    )


# ---- EVERYTHING BELOW IS STILL IN THIS .PY FILE ----
# Create the sequence automatically BEFORE the users table is created.
# (PostgreSQL-specific)
event.listen(
    User.__table__,
    "before_create",
    DDL("CREATE SEQUENCE IF NOT EXISTS user_code_seq START WITH 1 INCREMENT BY 1;")
)
