"""add notifications table

Revision ID: 01c067df2672
Revises: 28e7770dce79
Create Date: 2026-02-14 17:15:53.295812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01c067df2672'
down_revision: Union[str, Sequence[str], None] = '28e7770dce79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bell_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.String(length=8), nullable=False),
    sa.Column('recipient_id', sa.String(length=8), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Singapore')"), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application_form.application_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bell_notifications')
    # ### end Alembic commands ###
