"""fix job_id to uuid

Revision ID: 18eb2e4dca10
Revises: 0e916a27d6dd
Create Date: 2026-02-13 01:45:20.497625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18eb2e4dca10'
down_revision: Union[str, Sequence[str], None] = '0e916a27d6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reviewJobs_job_id_key'), 'reviewJobs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('reviewJobs_job_id_key'), 'reviewJobs', ['job_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
