"""modified app table v2

Revision ID: 1b2469017d72
Revises: bf0ef785eb3a
Create Date: 2026-03-16 15:15:07.034516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2469017d72'
down_revision: Union[str, Sequence[str], None] = 'bf0ef785eb3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_form', sa.Column('provider_session_id', sa.String(length=255), nullable=True))
    op.create_table(
        "risk_config_list_version",
        sa.Column("list_name", sa.String(length=100), primary_key=True),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=False),
            nullable=False,
            server_default=sa.text("(now() AT TIME ZONE 'Asia/Singapore')")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_form', 'provider_session_id')
    op.drop_table("risk_config_list_version")
    # ### end Alembic commands ###
