"""modified app table v2

Revision ID: 1b2469017d72
Revises: bf0ef785eb3a
Create Date: 2026-03-16 15:15:07.034516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2469017d72'
down_revision: Union[str, Sequence[str], None] = 'bf0ef785eb3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_form', sa.Column('provider_session_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_form', 'provider_session_id')
    # ### end Alembic commands ###
