"""modified config list table v2

Revision ID: 1f785fc4e661
Revises: 08f912a8ce7e
Create Date: 2026-03-19 22:20:12.656578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f785fc4e661'
down_revision: Union[str, Sequence[str], None] = '08f912a8ce7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('risk_config_list', 'item_value',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risk_config_list', 'item_value',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('documents', 'extracted_data')
    # ### end Alembic commands ###
