"""add action requests for escalation

Revision ID: 2fa589b11a72
Revises: 8b805296b8b7
Create Date: 2026-03-03 22:36:31.774697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa589b11a72'
down_revision: Union[str, Sequence[str], None] = '8b805296b8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_requests',
    sa.Column('action_request_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=8), nullable=False),
    sa.Column('reviewer_id', sa.String(length=8), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Singapore')"), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','SUBMITTED','CLOSED')", name='chk_action_requests_status'),
    sa.ForeignKeyConstraint(['application_id'], ['application_form.application_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_request_id'),
    sa.UniqueConstraint('action_request_id')
    )
    op.create_index(op.f('ix_action_requests_application_id'), 'action_requests', ['application_id'], unique=False)
    op.create_index(op.f('ix_action_requests_reviewer_id'), 'action_requests', ['reviewer_id'], unique=False)
    op.create_table('action_request_items',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('action_request_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('document_name', sa.String(length=500), nullable=True),
    sa.Column('question_text', sa.String(length=500), nullable=True),
    sa.Column('answer_text', sa.String(length=1500), nullable=True),
    sa.Column('fulfilled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("(item_type <> 'DOCUMENT') OR (document_name IS NOT NULL AND length(trim(document_name)) > 0)", name='chk_action_request_items_document_name_required'),
    sa.CheckConstraint("(item_type <> 'QUESTION') OR (question_text IS NOT NULL AND length(trim(question_text)) > 0)", name='chk_action_request_items_question_text_required'),
    sa.CheckConstraint("item_type IN ('DOCUMENT','QUESTION')", name='chk_action_request_items_type'),
    sa.ForeignKeyConstraint(['action_request_id'], ['action_requests.action_request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_index(op.f('ix_action_request_items_action_request_id'), 'action_request_items', ['action_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_request_items_action_request_id'), table_name='action_request_items')
    op.drop_table('action_request_items')
    op.drop_index(op.f('ix_action_requests_reviewer_id'), table_name='action_requests')
    op.drop_index(op.f('ix_action_requests_application_id'), table_name='action_requests')
    op.drop_table('action_requests')
    # ### end Alembic commands ###
