"""modified risk vc table

Revision ID: 465cd428052b
Revises: PUT_NEW_REVISION_ID_HERE
Create Date: 2026-04-08 11:31:52.940192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '465cd428052b'
down_revision: Union[str, Sequence[str], None] = 'PUT_NEW_REVISION_ID_HERE'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_config_list_version')
    op.create_table(
        "risk_rule_category_version",
        sa.Column("category", sa.String(length=20), primary_key=True),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=False),
            nullable=False,
            server_default=sa.text("(now() AT TIME ZONE 'Asia/Singapore')")
        ),
    )

    op.execute("""
        INSERT INTO risk_rule_category_version (category, version, updated_at)
        SELECT DISTINCT category, 1, (now() AT TIME ZONE 'Asia/Singapore')
        FROM risk_rule
        ON CONFLICT (category) DO NOTHING
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_config_list_version',
    sa.Column('list_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Singapore'::text)"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('list_name', name=op.f('risk_config_list_version_pkey'))
    )
    op.drop_table("risk_rule_category_version")
    # ### end Alembic commands ###
