"""edited field types

Revision ID: 5e96dace0b73
Revises: 9cf097ce7232
Create Date: 2026-02-13 01:33:37.361424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e96dace0b73'
down_revision: Union[str, Sequence[str], None] = '9cf097ce7232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'reviewJobs', ['job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviewJobs', type_='unique')
    # ### end Alembic commands ###
