"""add risk fields to reviewjobs

Revision ID: 8b805296b8b7
Revises: 26f1648c074a
Create Date: 2026-02-26 21:40:02.770871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b805296b8b7'
down_revision: Union[str, Sequence[str], None] = '26f1648c074a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_form', sa.Column('last_saved_step', sa.Integer(), nullable=True))
    op.add_column('reviewJobs', sa.Column('risk_score', sa.Integer(), nullable=True))
    op.add_column('reviewJobs', sa.Column('risk_grade', sa.String(length=20), nullable=True))
    op.add_column('reviewJobs', sa.Column('rules_triggered', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('reviewJobs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviewJobs', 'completed_at')
    op.drop_column('reviewJobs', 'rules_triggered')
    op.drop_column('reviewJobs', 'risk_grade')
    op.drop_column('reviewJobs', 'risk_score')
    op.drop_column('application_form', 'last_saved_step')
    # ### end Alembic commands ###
