"""created new rules engine table v1.1

Revision ID: 8b8fa5b0285c
Revises: e597ac274bea
Create Date: 2026-03-13 01:16:09.590621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8fa5b0285c'
down_revision: Union[str, Sequence[str], None] = 'e597ac274bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Singapore')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Singapore')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code', name='uq_risk_rule_code')
    )
    op.create_index(op.f('ix_risk_rule_rule_code'), 'risk_rule', ['rule_code'], unique=True)
    op.create_table('risk_rule_condition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('condition_group', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('operator', sa.String(length=30), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('string_value', sa.String(length=255), nullable=True),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.Column('list_name', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('trigger_description', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Singapore')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Singapore')"), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['risk_rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_rule_condition')
    op.drop_index(op.f('ix_risk_rule_rule_code'), table_name='risk_rule')
    op.drop_table('risk_rule')
    # ### end Alembic commands ###
