"""created liveness table v1

Revision ID: bf0ef785eb3a
Revises: 8b8fa5b0285c
Create Date: 2026-03-14 20:55:20.706060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf0ef785eb3a'
down_revision: Union[str, Sequence[str], None] = '8b8fa5b0285c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liveness_detection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.String(length=8), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_session_id', sa.String(length=100), nullable=False),
    sa.Column('provider_session_number', sa.Integer(), nullable=True),
    sa.Column('workflow_id', sa.String(length=100), nullable=True),
    sa.Column('provider_session_url', sa.String(length=500), nullable=True),
    sa.Column('overall_status', sa.String(length=50), nullable=True),
    sa.Column('manual_review_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('document_number_masked', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('issuing_state_code', sa.String(length=10), nullable=True),
    sa.Column('formatted_address', sa.String(length=500), nullable=True),
    sa.Column('id_verification_status', sa.String(length=50), nullable=True),
    sa.Column('liveness_status', sa.String(length=50), nullable=True),
    sa.Column('liveness_score', sa.Float(), nullable=True),
    sa.Column('face_match_status', sa.String(length=50), nullable=True),
    sa.Column('face_match_score', sa.Float(), nullable=True),
    sa.Column('has_duplicate_identity_hit', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_duplicate_face_hit', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application_form.application_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liveness_detection')
    # ### end Alembic commands ###
