"""add action requests for escalation 2

Revision ID: e1ba0fa2b3fd
Revises: 2fa589b11a72
Create Date: 2026-03-04 01:27:44.217634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ba0fa2b3fd'
down_revision: Union[str, Sequence[str], None] = '2fa589b11a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_request_items', sa.Column('document_desc', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'action_request_items', ['item_id'])
    op.create_unique_constraint(None, 'action_requests', ['action_request_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'action_requests', type_='unique')
    op.drop_constraint(None, 'action_request_items', type_='unique')
    op.drop_column('action_request_items', 'document_desc')
    # ### end Alembic commands ###
