"""created auditTrail v2

Revision ID: ef1a8fdfda08
Revises: f9ecd63ba71f
Create Date: 2026-03-11 20:24:53.427978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1a8fdfda08'
down_revision: Union[str, Sequence[str], None] = 'f9ecd63ba71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_trail', 'actor_id',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('audit_trail', 'actor_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('audit_trail', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_unique_constraint(None, 'audit_trail', ['audit_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_trail', type_='unique')
    op.alter_column('audit_trail', 'event_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('audit_trail', 'actor_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('audit_trail', 'actor_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    # ### end Alembic commands ###
