"""add new_table

Revision ID: f2391ad0ff3c
Revises: 9339eb5f46b0
Create Date: 2026-02-13 00:31:08.712033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2391ad0ff3c'
down_revision: Union[str, Sequence[str], None] = '9339eb5f46b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewJobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'QUEUED'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application_form.application_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_unique_constraint(None, 'application_form', ['application_id'])
    op.create_unique_constraint(None, 'user', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'application_form', type_='unique')
    op.drop_table('reviewJobs')
    # ### end Alembic commands ###
