"""modified action requests table

Revision ID: f5c5f524ad37
Revises: 0d9837ed5f2b
Create Date: 2026-04-14 03:28:19.615403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5c5f524ad37'
down_revision: Union[str, Sequence[str], None] = '0d9837ed5f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_rule_category_version')
    op.drop_table('risk_config_list_version')
    op.add_column('action_requests', sa.Column('ocr_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_requests', 'ocr_warnings')
    op.create_table('risk_config_list_version',
    sa.Column('list_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Singapore'::text)"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('list_name', name=op.f('risk_config_list_version_pkey'))
    )
    op.create_table('risk_rule_category_version',
    sa.Column('category', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Singapore'::text)"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('category', name=op.f('risk_rule_category_version_pkey'))
    )
    # ### end Alembic commands ###
