"""modified action request table v2

Revision ID: f84b6ee67f09
Revises: 015ac56ff553
Create Date: 2026-03-26 13:12:45.365770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f84b6ee67f09'
down_revision: Union[str, Sequence[str], None] = '015ac56ff553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_request_items', sa.Column('submitted_document_name', sa.String(length=500), nullable=True))
    op.add_column('action_request_items', sa.Column('substitution_reason', sa.String(length=1500), nullable=True))
    op.add_column('action_request_items', sa.Column('is_substitute', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_request_items', 'is_substitute')
    op.drop_column('action_request_items', 'substitution_reason')
    op.drop_column('action_request_items', 'submitted_document_name')
    # ### end Alembic commands ###
