"""created new risk_config_list table v3

Revision ID: f95c606dd951
Revises: feca1d66d8db
Create Date: 2026-03-12 16:54:15.831467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95c606dd951'
down_revision: Union[str, Sequence[str], None] = 'feca1d66d8db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_config_list', sa.Column('item_label', sa.String(length=255), nullable=False))
    op.alter_column('risk_config_list', 'item_value',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risk_config_list', 'item_value',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('risk_config_list', 'item_label')
    # ### end Alembic commands ###
