"""created auditTrail v1

Revision ID: f9ecd63ba71f
Revises: 926aa03335b9
Create Date: 2026-03-11 00:02:19.175122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ecd63ba71f'
down_revision: Union[str, Sequence[str], None] = '926aa03335b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trail',
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=8), nullable=False),
    sa.Column('actor_id', sa.String(length=8), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Singapore')"), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application_form.application_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audit_id'),
    sa.UniqueConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_trail_application_id'), 'audit_trail', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_trail_application_id'), table_name='audit_trail')
    op.drop_table('audit_trail')
    # ### end Alembic commands ###
