"""created new risk_config_list table v2

Revision ID: feca1d66d8db
Revises: 84b349db81dd
Create Date: 2026-03-12 16:37:46.548716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feca1d66d8db'
down_revision: Union[str, Sequence[str], None] = '84b349db81dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_config_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('list_name', sa.String(length=100), nullable=False),
    sa.Column('item_value', sa.String(length=255), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Singapore')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Singapore')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_name', 'item_value', name='uq_risk_config_list_name_value')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_config_list')
    # ### end Alembic commands ###
